# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Copy package files and install dependencies
COPY package*.json ./

RUN npm install --ignore-scripts

# Copy the rest of the application
COPY . .

# Build the project
RUN npm run build

# Set a default API key for development/testing
ENV PANOS_API_KEY=demo-key

# Expose a port if needed (uncomment if necessary)
# EXPOSE 3000

# Start the server
CMD [ "npm", "start" ]
